esphome:
  name: "minimal-monolith"
  on_boot:
    priority: -100
    then:
      - output.turn_on: pa_ctrl
      - output.turn_on: dac_ctrl
      - light.turn_on:
          id: led_ring
          effect: Idle Rainbow
          brightness: 80%
      - delay: 3s
      - light.turn_on:
          id: led_ring
          effect: Startup Scan
          red: 0%
          blue: 100%
          green: 0%
      - media_player.speaker.play_on_device_media_file:
          media_file: starwars_file
      - wait_until:
          condition:
            wifi.connected:
      - light.turn_on:
          id: led_ring
          effect: Working
          red: 0%
          blue: 100%
          green: 0%
      - delay: 1s
      - script.execute: reset_led

esp32:
  board: esp32dev
  flash_size: 16MB
  partitions: partitions.csv
  framework:
    type: esp-idf
    version: 4.4.8
    platform_version: 5.4.0
    sdkconfig_options:
      CONFIG_FREERTOS_MAX_TASK_NAME_LEN: "16"
      CONFIG_LOG_MAXIMUM_LEVEL: "3"
      CONFIG_FREERTOS_NUMBER_OF_CORES: "2"
      CONFIG_ESP32_DEFAULT_CPU_FREQ_MHZ: "160"
      CONFIG_ESP32_WIFI_IRAM_OPT: "y"
      CONFIG_ESP32_WIFI_RX_IRAM_OPT: "y"
      CONFIG_I2S_ISR_IRAM_LEVEL: "3"
      CONFIG_ESP_MAIN_TASK_STACK_SIZE: "8192"
      CONFIG_SYSTEM_EVENT_TASK_STACK_SIZE: "4096"
      CONFIG_ESP32_SPIRAM_SUPPORT: "y"
      CONFIG_SPIRAM_BOOT_INIT: "y"
      CONFIG_SPIRAM_USE_MALLOC: "y"
      CONFIG_ESP_TASK_WDT: "y"
      CONFIG_ESP_TASK_WDT_TIMEOUT_S: "300"

psram:
  mode: quad
  speed: 80MHz

external_components:
  - source:
      type: local
      path: esphome/components
    components: [cx_audio, cx_i2s]

logger:
  level: DEBUG

api:

wifi:
  ssid: "HUAWEI-1CFWD0"
  password: "8113540586"
  power_save_mode: none

cx_audio:
  id: my_cx_audio
  use_firmware: false

output:
  - platform: gpio
    id: pa_ctrl
    pin: GPIO22
  - platform: gpio
    id: dac_ctrl
    pin: GPIO4

microphone:
  - platform: cx_i2s
    id: my_mic
    cx_audio_id: my_cx_audio
    mic_gain: -10dB

speaker:
  - platform: cx_i2s
    id: my_speaker
    cx_audio_id: my_cx_audio

media_player:
  - platform: speaker
    id: speaker_player
    name: "Monolith Player"
    announcement_pipeline:
      speaker: my_speaker
      sample_rate: 48000
      num_channels: 2
    files:
      - id: starwars_file
        file: starwars.wav

voice_assistant:
  microphone: my_mic
  speaker: my_speaker
  on_listening:
    - light.turn_on:
        id: led_ring
        blue: 80%
        red: 80%
        green: 80%
        brightness: 80%
        effect: Wakeword
  on_end:
    - script.execute: reset_led
  on_error:
    - light.turn_on:
        id: led_ring
        blue: 0%
        red: 100%
        green: 0%
        brightness: 80%
        effect: none
    - delay: 1s
    - script.execute: reset_led

# =============== SCRIPTS ===============
script:
  - id: reset_led
    mode: restart
    then:
      - delay: 50ms
      - if:
          condition:
            switch.is_on: night_mode
          then:
            - light.turn_on:
                id: led_ring
                brightness: 20%
                effect: Idle Rainbow
          else:
            - light.turn_on:
                id: led_ring
                brightness: 60%
                effect: Idle Rainbow

# =============== SWITCHES ===============
switch:
  - platform: template
    name: Night Mode Switch
    id: night_mode
    optimistic: true
    restore_mode: RESTORE_DEFAULT_ON
    entity_category: config
    on_turn_on:
      - script.execute: reset_led
    on_turn_off:
      - script.execute: reset_led

# =============== LIGHT ===============
light:
  - platform: esp32_rmt_led_strip
    id: led_ring
    rmt_channel: 0
    name: "LED Ring"
    pin: GPIO27
    num_leds: 24
    rgb_order: GRB
    chipset: ws2812
    restore_mode: ALWAYS_ON
    default_transition_length: 0s
    effects:
      - pulse:
          name: "Pulse"
          transition_length: 0.5s
          update_interval: 0.5s
      - addressable_twinkle:
          name: "Working"
          twinkle_probability: 80%
          progress_interval: 50ms
      - addressable_color_wipe:
          name: "Wakeword"
          colors:
            - red: 0%
              green: 100%
              blue: 0%
              num_leds: 12
          add_led_interval: 40ms
          reverse: false
      - addressable_color_wipe:
          name: "Power"
          colors:
            - red: 100%
              green: 0%
              blue: 0%
              num_leds: 12
          add_led_interval: 50ms
          reverse: false
      - addressable_rainbow:
          name: "Idle Rainbow"
          speed: 10
          width: 24
      - addressable_scan:
          name: "Startup Scan"
          move_interval: 40ms
          scan_width: 6

sensor:
  - platform: sound_level
    microphone: my_mic
    passive: false
    rms:
      name: "RMS"
    peak:
      name: "Peak"
