esphome:
  name: "minimal-monolith"
  platformio_options:
    board_build.partitions: partitions_no_ota.csv
  on_boot:
    priority: -200
    then:
      - delay: 2s
      - media_player.speaker.play_on_device_media_file:
          media_file: starwars_file

esp32:
  board: esp32dev
  framework:
    type: esp-idf
    version: 4.4.8
    platform_version: 5.4.0
    sdkconfig_options:
      CONFIG_FREERTOS_MAX_TASK_NAME_LEN: "16"
      CONFIG_LOG_MAXIMUM_LEVEL: "3"
      CONFIG_FREERTOS_NUMBER_OF_CORES: "2"
      CONFIG_ESP32_DEFAULT_CPU_FREQ_MHZ: "160"
      CONFIG_ESP32_WIFI_IRAM_OPT: "y"
      CONFIG_ESP32_WIFI_RX_IRAM_OPT: "y"
      CONFIG_I2S_ISR_IRAM_LEVEL: "3"
      CONFIG_ESP_MAIN_TASK_STACK_SIZE: "8192"
      CONFIG_SYSTEM_EVENT_TASK_STACK_SIZE: "4096"
      CONFIG_ESP32_SPIRAM_SUPPORT: "y"
      CONFIG_SPIRAM_BOOT_INIT: "y"
      CONFIG_SPIRAM_USE_MALLOC: "y"
      CONFIG_ESP_TASK_WDT_TIMEOUT_S: "30"

psram:
  mode: quad
  speed: 80MHz

external_components:
  - source:
      type: local
      path: esphome_src/esphome/components
    components: [cx_audio, cx_i2s]

logger:
  level: DEBUG

api:

wifi:
  ssid: "HUAWEI-1CFWD0"
  password: "8113540586"
  power_save_mode: none

cx_audio:
  id: my_cx_audio

microphone:
  - platform: cx_i2s
    id: my_mic
    cx_audio_id: my_cx_audio

speaker:
  - platform: cx_i2s
    id: my_speaker
    cx_audio_id: my_cx_audio

media_player:
  - platform: speaker
    id: speaker_player
    name: "Monolith Player"
    announcement_pipeline:
      speaker: my_speaker
      sample_rate: 48000
      num_channels: 2
    files:
      - id: starwars_file
        file: starwars.wav

voice_assistant:
  microphone: my_mic
  speaker: my_speaker
